### ISSUE TITLE
Reviews of design doc

### ISSUE THREAD

**Issue by aracpyon** [sinoyuco/HipTrip#1]
Great job on design doc, Sinan! Here are my reviews:

**MVPs**
- [ ] non-logged-in users should be able to see spots and reviews, but can't make reservations and create spots
- [ ] make sure to have a full CRUD functionality on at least one MVP. 
- [ ] ensure bookings can be edited. 

**Schema**
- [ ] `Users`: add `fname` and `lname` columns
- [ ]  `Spots`: add `latitude` and `longitude` columns (will be useful for search later)
- [ ] `Bookings`: add `num_guests`, `total_price` column
- [ ] `Reviews`: add `rating` column 
- [ ] consider to make tables for `campsite_area`, `amenities` and `essentials` with foreign key of `spot_id` and boolean columns.

**Comment by aracpyon** [comment]
Hi Sinan, great job on your state! Your sample state looks great so far, just a minor heads-up:

**state**
- [ ] `amenities`, `essentials`, `campsite_area` are belonging to `Spots`, which means we can build a n association between them. We can make amenities, essentials and campsite_area slices nested to individual spot, just like individual `pokemon` had an array of `item_ids`. I will explain this during the flex time tonight.

**Comment by sinoyuco** [comment]
Hey Ara,
I implemented the simple choice you mentioned before the polymorphic joins table to my design docs for the time being because I was unclear how the polymorphic joins table would exactly work, even after looking at brian's design docs that you mentioned. Even in this simple approach with the 3 columns (id, amenity type and listing_id), I am having a hard time how fields with data type that are not boolean will be represented in these tables, (like max_#_of guests), or should they be instead moved into the spot(listing) table. This is later in the project I guess so you can answer when you come back on Thursday, just passing a note here. Thanks for the help.
